const ICON_MAP = [
  { keywords: ["onion"], icon: "🧅" },
  { keywords: ["garlic"], icon: "🧄" },
  { keywords: ["tomato"], icon: "🍅" },
  { keywords: ["cheese"], icon: "🧀" },
  { keywords: ["beef", "steak"], icon: "🥩" },
  { keywords: ["chicken"], icon: "🍗" },
  { keywords: ["pork", "bacon", "ham"], icon: "🥓" },
  { keywords: ["fish", "salmon", "tuna"], icon: "🐟" },
  { keywords: ["shrimp", "prawn"], icon: "🦐" },
  { keywords: ["egg"], icon: "🥚" },
  { keywords: ["milk", "cream", "sour cream"], icon: "🥛" },
  { keywords: ["butter"], icon: "🧈" },
  { keywords: ["oil"], icon: "🫒" },
  { keywords: ["flour"], icon: "🌾" },
  { keywords: ["sugar"], icon: "🍬" },
  { keywords: ["salt"], icon: "🧂" },
  { keywords: ["pepper", "jalape"], icon: "🌶️" },
  { keywords: ["rice"], icon: "🍚" },
  { keywords: ["pasta", "noodle", "spaghetti"], icon: "🍝" },
  { keywords: ["bread", "tortilla", "shell", "bun"], icon: "🫓" },
  { keywords: ["lemon"], icon: "🍋" },
  { keywords: ["lime"], icon: "🟢" },
  { keywords: ["orange"], icon: "🍊" },
  { keywords: ["apple"], icon: "🍎" },
  { keywords: ["pear"], icon: "🍐" },
  { keywords: ["peach"], icon: "🍑" },
  { keywords: ["watermelon"], icon: "🍉" },
  { keywords: ["kiwi"], icon: "🥝" },
  { keywords: ["mango"], icon: "🥭" },
  { keywords: ["cherry"], icon: "🍒" },
  { keywords: ["banana"], icon: "🍌" },
  { keywords: ["strawberry"], icon: "🍓" },
  { keywords: ["blueberry"], icon: "🫐" },
  { keywords: ["grape"], icon: "🍇" },
  { keywords: ["pineapple"], icon: "🍍" },
  { keywords: ["cucumber"], icon: "🥒" },
  { keywords: ["pepper", "bell pepper"], icon: "🫑" },
  { keywords: ["mushroom"], icon: "🍄" },
  { keywords: ["lettuce", "spinach", "kale"], icon: "🥬" },
  { keywords: ["cilantro", "parsley", "basil", "herb", "mint"], icon: "🌿" },
  { keywords: ["avocado", "guacamole"], icon: "🥑" },
  { keywords: ["potato"], icon: "🥔" },
  { keywords: ["carrot"], icon: "🥕" },
  { keywords: ["lentil", "bean"], icon: "🫘" },
  { keywords: ["stock", "broth", "soup", "seasoning"], icon: "🍲" },
  { keywords: ["water"], icon: "💧" },
  { keywords: ["ice"], icon: "🧊" },
  { keywords: ["wine"], icon: "🍷" },
  { keywords: ["pan", "skillet"], icon: "🍳" },
  { keywords: ["pot"], icon: "🍲" },
  { keywords: ["knife"], icon: "🔪" },
  { keywords: ["bowl"], icon: "🥣" },
  { keywords: ["oven"], icon: "🔥" },
  { keywords: ["blender"], icon: "🌀" },
  { keywords: ["whisk", "spoon", "spatula"], icon: "🥄" },
  { keywords: ["strainer"], icon: "🔍" },
  { keywords: ["cutting board", "board"], icon: "🪵" },
  { keywords: ["grill"], icon: "🔥" },
  { keywords: ["timer", "clock"], icon: "⏱️" },
  { keywords: ["plate"], icon: "🍽️" },
];

export function getIconForItem(name) {
  const lower = (name || "").toLowerCase();
  for (const entry of ICON_MAP) {
    if (entry.keywords.some((keyword) => lower.includes(keyword))) {
      return entry.icon;
    }
  }
  return "•";
}